### ISSUE TITLE
hellooooooooou

### ISSUE THREAD

**Issue by Teramystic** [DeathDefying/sc-guide#2]
hii I have few question for you.
ehm first ) how to contact
second ) how much for 3rd boss calling mechanics

**Comment by DeathDefying** [comment]
contact me for what exactly? and a few days until i release the last boss

**Comment by Teramystic** [comment]
ehm well you said -(3rd WIP)- though you gonna make benefits from this :< my baddd

**Comment by DeathDefying** [comment]
@Teramystic If you like my work and want to donate, dm me Yang#0966. But my mods are free
