### ISSUE TITLE
Last Boss Backswipes - Suggestion

### ISSUE THREAD

**Issue by Peckspas** [DeathDefying/sc-guide#4]
Those backswipes and double backswipes are already called by this guide and its working well but they should get announce atleast one or two whole seconds earlier to even matter.
Is it possible to call them out right when the attack pattern for swipes start, so that there is still time to react to them? Currently the guide calls them out the exact same second they happen and that is functional but not useful.
Would be great if its possible to tweak this.

**Comment by DeathDefying** [comment]
I'll take a look at it and see if that's possible, I did exactly what you said for the left/right swipes, so this might possible as well.

**Comment by DeathDefying** [comment]
I'll take a look at it and see if that's possible, I did exactly what you said for the left/right swipes, so this should be possible as well.

**Comment by DeathDefying** [comment]
@Peckspas Added. Now it will call as soon as it starts doing the combo and right before it does the swipe
